# Generated by Django 3.0.5 on 2020-04-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
