# Generated by Django 3.0.5 on 2020-04-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrado',
            name='comentario',
        ),
    ]
