# Generated by Django 3.0.5 on 2020-04-26 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(choices=[('egresado', 'egresado'), ('admin', 'admin'), ('superadmin', 'superadmin')], default='egresado', max_length=100, verbose_name='Tipo de usuario')),
                ('imagen_Perfil', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=users.models.upload_location, width_field='width_field')),
                ('website', models.URLField(blank=True)),
                ('telefono', models.IntegerField(default=0)),
                ('ciudad', models.TextField(max_length=20)),
                ('dni_administrador', models.CharField(max_length=20)),
                ('fecha_Nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('indef', 'Indefinido'), ('masc', 'Masculino'), ('fem', 'Femenino')], default='indef', max_length=6)),
                ('confirmation_handling_sensitive_data', models.BooleanField(default=True)),
                ('biografia', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
